Header update because there were errors checking out the submodule commit:
git submodule update
error: Server does not allow request for unadvertised object e2f634efdecbae286fe80b758b0447928aee41e3
Fetched in submodule path 'header', but it did not contain e2f634efdecbae286fe80b758b0447928aee41e3. Direct fetching of that commit failed.